version: "3"

services:
  gkeepbringsync:
    image: ghcr.io/swaggeroo/gkeepbringsync
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data # google auth token inside keep it secret this can access your google account
    environment:
      # Google
      - GOOGLE_EMAIL=<your email>
      - GOOGLE_PASSWORD=<your password>
      - KEEP_LIST_ID=<your list id>

      # Bring
      - BRING_EMAIL=<your email>
      - BRING_PASSWORD=<your password>


      # OPTIONAL
      #- SYNC_MODE=0 # 0 = bidirectional, 1 = bring master, 2 = google master
      #- TIMEOUT=60 # minutes
      #- BRING_LIST_NAME=Groceries
