name: Bump Version Renovate

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: github.actor == 'renovate[bot]'
    permissions:
      contents: write
    uses: Swaggeroo/ci-workflows/.github/workflows/pr-bump-version.yaml@v1.0.0
    with:
      version_file: version.txt
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
